config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'home#top'
  get 'home/about'
  get '/search' => 'search#search'
  post 'follow/:id' => 'relationships#follow', as: 'follow' # フォローする
  post 'unfollow/:id' => 'relationships#unfollow', as: 'unfollow' # フォロー外す
  resources :users, only: [:show ,:edit ,:update ,:index, :destroy ] do
    resource :relationships, only: [:create, :destroy]
  get 'followings' => 'relationships#followings', as: 'followings'
  get 'followers' => 'relationships#followers', as: 'followers'
  end
  resources :books, only: [:new, :create,:index, :show, :destroy ,:edit ,:update] do
   resources :book_comments, only: [:create, :destroy]
   resource :favorites, only: [:create, :destroy]
 end
 end

app/models/relationship.rb
class Relationship < ApplicationRecord
    belongs_to :follower, class_name: "User"
    belongs_to :followed, class_name: "User"
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
  def follow
  current_user.follow(params[:id])
  redirect_to request.referer
  end

  def unfollow
  current_user.unfollow(params[:id])
  redirect_to request.referer
  end

  def followings
    @user = User.find(params[:user_id])
    @users = @user.following_user
  end

  def followers
    @user = User.find(params[:user_id])
    @users = @user.follower_user
  end

  def index
    @users = User.all
    @user = current_user
    @book = Book.new
  end

end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/views/relationships/followers.html.erb
<h2>Follower Users</h2>
<% if @users.exists? %>
  <table class="table table-hover table-inverse">
          <thead>
            <tr>
              <th>image</th>
              <th>name</th><th></th><th></th><th></th><th></th>
            </tr>
              <% @users.each do |user| %>
            <tbody>
              <td><%= link_to attachment_image_tag user, :profile_image, :fill, 60, 60, fallback: "no_image.jpg" %></td>
              <td><%= user.name %></td>

              <td>フォロー数:<%= user.follower.count %></td>
              <td>フォロワー数：<%= user.followed.count %></td>

              <td><% if current_user.following?(user) %>
                  <%= link_to 'フォロー外す', unfollow_path(user.id), method: :POST %>
                  <% else %>
                  <%= link_to 'フォローする', follow_path(user.id), method: :POST %>
                  <% end %></td>
              <td><%= link_to "Show", user_path(user) %></td>
            </tbody>
              <% end %>
         </thead>
        </table>
      </div>
<% else %>
  <p>ユーザーはいません</p>
<% end %>

app/views/relationships/followings.html.erb
<h2>Follow Users</h2>
<% if @users.exists? %>
   <table class="table table-hover table-inverse">
          <thead>
            <tr>
              <th>image</th>
              <th>name</th><th></th><th></th><th></th><th></th>
            </tr>
              <% @users.each do |user| %>
            <tbody>
              <td><%= link_to attachment_image_tag user, :profile_image, :fill, 60, 60, fallback: "no_image.jpg" %></td>
              <td><%= user.name %></td>

              <td>フォロー数:<%= user.follower.count %></td>
              <td>フォロワー数：<%= user.followed.count %></td>

              <td><% if current_user.following?(user) %>
                  <%= link_to 'フォロー外す', unfollow_path(user.id), method: :POST %>
                  <% else %>
                  <%= link_to 'フォローする', follow_path(user.id), method: :POST %>
                  <% end %></td>
              <td><%= link_to "Show", user_path(user) %></td>
            </tbody>
              <% end %>
         </thead>
        </table>
      </div>
<% else %>
  <p>ユーザーはいません</p>
<% end %>