config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'home#top'
  get 'home/about'
  get '/search' => 'search#search'
  post 'follow/:id' => 'relationships#follow', as: 'follow' # フォローする
  post 'unfollow/:id' => 'relationships#unfollow', as: 'unfollow' # フォロー外す
  resources :users, only: [:show ,:edit ,:update ,:index, :destroy ] do
    resource :relationships, only: [:create, :destroy]
  get 'followings' => 'relationships#followings', as: 'followings'
  get 'followers' => 'relationships#followers', as: 'followers'
  end
  resources :books, only: [:new, :create,:index, :show, :destroy ,:edit ,:update] do
   resources :book_comments, only: [:create, :destroy]
   resource :favorites, only: [:create, :destroy]
 end
 end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy
  has_many :follower, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :followed, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  has_many :following_user, through: :follower, source: :followed
  has_many :follower_user, through: :followed, source: :follower
  attachment :profile_image

# ユーザーをフォローする
def follow(user_id)
  follower.create(followed_id: user_id)
end

# ユーザーのフォローを外す
def unfollow(user_id)
  follower.find_by(followed_id: user_id).destroy
end

# フォローしていればtrueを返す
def following?(user)
  following_user.include?(user)
end

  validates :name, presence: true,length:{minimum:2,maximum:20},uniqueness: true
  validates :introduction,length:{maximum:50}
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!



  def new
  end

  def create
  end

  def index
    @users = User.all
    @user = current_user
    @book = Book.new
  end

  def show
    @user = User.find(params[:id])
    @books = @user.books
    @book = Book.new
    @users = User.all
  end

  def edit
    @user = User.find(params[:id])
    if @user == current_user
    render "edit"
    else
    redirect_to user_path(current_user)
    end
  end

  def update
    @user = User.find(params[:id])
    if  @user.update(user_params)
    flash[:notice] = "User was successfully updated."
    redirect_to user_path(@user)
    else
      flash[:notice] = "User was errored."
      render "users/edit"
    end
  end

  def destroy
  end

  def followings
    @followings = @user.following_users
  end

  def followers
    @followers = @user.follower_users
  end

private

  def user_params
    params.require(:user).permit(:name,:introduction, :profile_image)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_list.html.erb
<h2>User info</h2>
  <p><%= attachment_image_tag user, :profile_image, :fill, 100, 100, format: 'jpeg', fallback: "no_image.jpg" %></p>

<%= form_with model: @user, local:true do |f| %>

  <table class="table">
    <tr>
    <th>name</th>
    <th><%= user.name %></th>
    </tr>

    <tr>
    <th>introduction</th>
    <th><%= user.introduction %></th>
    </tr>

    <tr>
    <th>follows</th>
    <th><%= link_to user.follower.count,user_followings_path(user.id) %></th>
    </tr>

    <tr>
    <th>followers</th>
    <th><%= link_to user.followed.count,user_followers_path(user.id)%></th>
    </tr>
  </table>
<% end %>

  <div class="row"><%= link_to " ",edit_user_path(user), class:'btn btn-outline-secondary btn-block fas fa-user-cog edit_user_8378'%></div>

app/views/users/edit.html.erb
<% if @user.errors.any? %>
  <%= @user.errors.count %>errors occurred
  <% @user.errors.full_messages.each do |message| %>
    <%= message %>
  <% end %>
<% end %>

<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <h2>User info</h2>
        <%= form_with model: @user, local:true do |f| %>
          <p>Name <br>
        <%= flash[:notice] %>
        <%= f.text_field :name %></p>
          <p><label for="inputImage">Image</label><br>
        <%= f.attachment_field :profile_image, placeholder: "プロフィール画像" %></p>
          <p>Introduction <br>
        <%= f.text_area :introduction %></p>
          <p> </p>
        <%= f.submit 'Update User' ,class:"btn btn-secondary"%>
        <% end %>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<html lang="ja">

<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width,initial-scale=1.0">
  <script src="https://kit.fontawesome.com/15f7d4a3aa.js" crossorigin="anonymous"></script>
  <link rel="stylesheet" href="style3.css" />
  <title>Bookers2</title>
</head>

<body>
<% if @book.errors.any? %>
  <%= @book.errors.count %>errors occurred
  <% @book.errors.full_messages.each do |message| %>
    <%= message %>
  <% end %>
<% end %>

<%= flash[:notice] %>
<%= render 'search/header' %>
<div class="container px-5 px-sm-0">
  <div class="row">

    <div class="col-md-3">
      <%= render 'users/list', user: @user %>
      <%= render 'books/list', book: @book %>
    </div>

    <div class="col-md-8 offset-md-1">
        <h2>Users</h2>
        <table class="table table-hover table-inverse">
          <thead>
            <tr>
              <th>image</th>
              <th>name</th><th></th><th></th><th></th><th></th>
            </tr>
              <% @users.each do |user| %>
            <tbody>
              <td><%= link_to attachment_image_tag user, :profile_image, :fill, 60, 60, fallback: "no_image.jpg" %></td>

              <td><%= user.name %></td>

              <td>フォロー数:<%= user.follower.count %></td>
              <td>フォロワー数：<%= user.followed.count %></td>
              <% unless user == current_user %>
              <td><% if current_user.following?(user) %>
                  <%= link_to 'フォロー外す', unfollow_path(user.id), method: :POST %>
                  <% else %>
                  <%= link_to 'フォローする', follow_path(user.id), method: :POST %>
                  <% end %></td>
              <td><%= link_to "Show", user_path(user) %></td>
              <% end %>
            </tbody>
              <% end %>
         </thead>
        </table>
      </div>

    </div>
</div>
</body>

app/views/users/new.html.erb
<h1>画像投稿フォーム</h1>
<%= form_with model: @user, local:true do |f| %>
  <h4>画像</h4>
  <%= f.attachment_field :profile_image %>
  <h4>ショップ名</h4>
  <%= f.text_field :name %>
  <h4>説明</h4>
  <%= f.text_area :caption %>
  <%= f.submit '投稿' %>
<% end %>

app/views/users/show.html.erb
<body>
<%= render 'search/header' %>
<div class="container px-5 px-sm-0">
<div class="row">
<div class="col-md-3">
<%= render 'users/list', user: @user %>
<div class="row">
<div class="m-1">
<% unless @user == current_user %>
  <% if current_user.following?(@user) %>
    <td><%= link_to 'フォロー外す', unfollow_path(@user.id), method: :POST,class:"btn btn-sm btn-success edit_book_7295"%></td>
  <% else %>
    <td><%= link_to 'フォローする', follow_path(@user.id), method: :POST ,class:"btn btn-sm btn-success edit_book_7295"%></td>
  <% end %>
<% end %>
</div>
</div>
<br>
<%= render 'books/list', book: @book %>
</div>

<% if @book.errors.any? %>
  <%= @book.errors.count %>errors occurred
  <% @book.errors.full_messages.each do |message| %>
    <%= message %>
  <% end %>
<% end %>
<%= flash[:notice] %>



<div class="col-md-8 offset-md-1">
 <h2>Books</h2>

  <table class="table table-hover table-inverse">
  <thead>
  <tr>
  <th>Title</th>
  <th>Opinion</th>
  </tr>

  <% @books.each do |book| %>
  <tbody>
    <td><%= link_to user_path(book.user) do %>
<%= attachment_image_tag book.user, :profile_image, :fill, 60, 60, fallback: "no_image.jpg" %>
<% end %></td>
  <td><%= link_to book.title, book_path(book) %></td>
  <td><%= book.body %> </td>
  <td>コメント数：<%= book.book_comments.count %></td>
  </tbody>
  <% end %>
 </table>
 </div>
 </div>
</div>
</body>