config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'home#top'
  get 'home/about'
  get '/search' => 'search#search'
  post 'follow/:id' => 'relationships#follow', as: 'follow' # フォローする
  post 'unfollow/:id' => 'relationships#unfollow', as: 'unfollow' # フォロー外す
  resources :users, only: [:show ,:edit ,:update ,:index, :destroy ] do
    resource :relationships, only: [:create, :destroy]
  get 'followings' => 'relationships#followings', as: 'followings'
  get 'followers' => 'relationships#followers', as: 'followers'
  end
  resources :books, only: [:new, :create,:index, :show, :destroy ,:edit ,:update] do
   resources :book_comments, only: [:create, :destroy]
   resource :favorites, only: [:create, :destroy]
 end
 end

app/models/book.rb
class Book < ApplicationRecord
   belongs_to :user
   #attachment :image
   has_many :favorites, dependent: :destroy
   has_many :book_comments, dependent: :destroy
  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end
   validates :title, presence: true
   validates :body, presence: true ,length:{maximum:200}
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :authenticate_user!

  def new
   @book = Book.new
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
     if  @book.save
        flash[:notice] = "Book was successfully created."
        redirect_to book_path(@book)
     else
      @books = Book.all
      @user = current_user
      render "books/index"
     end
  end

  def index
     @books = Book.all
     @user = current_user
     @book = Book.new
  end

  def show
     @book = Book.find(params[:id])
     @user = @book.user
     @book_new = Book.new
     @book_comment = BookComment.new
     @book_comments = @book.book_comments.order(created_at: :desc)
  end

  def edit
      @book = Book.find(params[:id])
      if @book.user == current_user
          render "edit"
      else
          redirect_to books_path
      end
  end

  def destroy
    book = Book.find(params[:id])
    book.destroy
    redirect_to books_path
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
    flash[:notice] = "Book was successfully updated."
    redirect_to book_path(@book)
    else
    flash[:notice] = "Book was errored."
    render :edit
    end
  end

  private

  def book_params
    params.require(:book).permit(:title, :body)
  end
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_list.html.erb
<h2>New book</h2>
<%= form_with model: book, local:true do |f| %>

 <div class="form-group">
  <p>Title</p>
  <%= f.text_field :title %>
  </div>

  <div class="form-group">
  <p>Opinion</p>
  <%= f.text_area :body %>
  </div>

 <div class="form-group"><%= f.submit 'Create Book', class: 'btn btn-success '%></div>

<% end %>

app/views/books/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <h1>Editing Book</h1>
          <%= form_with model: @book, local:true do |f| %>
        <p>Title<br>
          <%= f.text_field :title %></p>
        <p>Opinion<br>
          <%= f.text_area :body %></p>
          <%= f.submit 'Update Book' ,class:"btn btn-success"%>
          <% end %>
         <p><%= link_to "Show", book_path(@book) %> | <%= link_to "Back", books_path %></p>
    </div>
  </div>
</div>

app/views/books/index.html.erb
<% if @book.errors.any? %>
  <%= @book.errors.count %>errors occurred
  <% @book.errors.full_messages.each do |message| %>
    <%= message %>
  <% end %>
<% end %>

<%= flash[:notice] %>

<%= render 'search/header' %>

<div class="container px-5 px-sm-0">
  <div class="row">
    <div class="col-md-3">
      <%= render 'users/list', user: @user %>
      <%= render 'books/list', book: @book %>
    </div>

    <div class="col-md-8 offset-md-1">
      <h2>Books</h2>
      <table class="table table-hover table-inverse">
       <thead>
        <tr>
          <th></th>
          <th>Title</th>
          <th>Opinion</th>
          <th colspan="3"></th>
        </tr>
      </thead>
       <% @books.each do |book| %>
      <tbody>
       <tr>
        <td><%= link_to user_path(book.user) do %>
          <%= attachment_image_tag book.user, :profile_image, :fill, 60, 60, fallback: "no_image.jpg" %>
          <% end %></td>
        <td><%= link_to book.title, book_path(book) %></td>
        <td><%= book.body %> </td>
        <td id="favorites_buttons_<%= book.id %>">
          <%= render 'favorites/favorite', book: book%>
        </td>
        <td>コメント数：<%= book.book_comments.count %></td>
       </tr>
      </tbody>
      <% end %>
      </table>
    </div>
  </div>
</div>

app/views/books/new.html.erb
<% if @book.errors.any? %>
  <%= @book.errors.count %>errors occurred
  <% @book.errors.full_messages.each do |message| %>
    <%= message %>
  <% end %>
<% end %>

<h1>New Book</h1>
<%= form_with model: @book, local:true do |f| %>
  <h4>Title</h4>
  <%= f.text_field :title %>
  <h4>Opinion</h4>
  <%= f.text_area :body %>
  <%= f.submit 'Create Book' %>
<% end %>

app/views/books/show.html.erb
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width,initial-scale=1.0">
  <script src="https://kit.fontawesome.com/15f7d4a3aa.js" crossorigin="anonymous"></script>
  <link rel="stylesheet" href="style3.css" />
  <title>Bookers2</title>
</head>

<body>
<% if @book_comment.errors.any? %>
  <%= @book_comment.errors.count %>errors occurred
  <% @book_comment.errors.full_messages.each do |message| %>
    <%= message %>
  <% end %>
<% end %>
<%= flash[:notice] %>


<div class="container px-5 px-sm-0">
  <div class="row">
    <div class="col-md-3">
      <%= render 'users/list', user: @user %>
      <%= render 'books/list', book: @book_new %>
    </div>

    <div class="col-md-8 offset-md-1">
      <h1>Book detail</h1>
      <table class="table table-hover table-inverse">
        <tbody>
          <% if @user.id == current_user.id %>
              <td><%= link_to user_path(@book.user) do %><%= attachment_image_tag @book.user, :profile_image, :fill, 60, 60, fallback: "no_image.jpg" %><br>
                <%= @user.name %><% end %></td>
              <td><%= @book.title %></td>
              <td><%= @book.body%></td>
              <td><%= link_to "Edit", edit_book_path(@book),class:"btn btn-sm btn-success edit_book_7295" %></td>
              <td><%= link_to "Destroy", book_path(@book), method: :delete ,class:"btn btn-sm btn-danger destroy_book_7295" ,data: { confirm: '本当に消しますか？' }%></td>
            <% if @book.favorited_by?(current_user) %>
              <td><%= link_to book_favorites_path(@book), method: :delete do %>♥<%= @book.favorites.count %> いいね<% end %></td>
            <% else %>
              <td><%= link_to book_favorites_path(@book), method: :post do %>♡<%= @book.favorites.count %> いいね<% end %></td>
            <% end %>
            <td>コメント件数：<%= @book.book_comments.count %></td>
            <% else %>
            <td><%= link_to user_path(@book.user) do %>
            <%= attachment_image_tag @book.user, :profile_image, :fill, 60, 60, fallback: "no_image.jpg" %><br>
            <%= @user.name %>
            <% end %></td>
            <td><%= @book.title %></td>
            <td><%= @book.body %></td>
            <% if @book.favorited_by?(current_user) %>
            <td>
              <%= link_to book_favorites_path(@book), method: :delete do %> ♥<%= @book.favorites.count %> いいね<% end %>
            </td>
            <% else %>
            <td>
              <%= link_to book_favorites_path(@book), method: :post do %>
              ♡<%= @book.favorites.count %> いいね
              <% end %>
            </td>
            <% end %>
            <td>コメント数：<%= @book.book_comments.count %></td>
            <% end %>
　　　　　</tbody>
　　　　</table>
　　　 </thead>
　　</table>

  　<div class="comments">
　　　<%= render partial: 'book_comments/index', locals: { book_comments: @book_comments } %>
　　</div>

　　<div class="new-comment">
　　　<%= render partial: 'book_comments/form', locals: { book_comment: @book_comment, book: @book } %>
　　</div>

　　</div>
　</div>
</div>