config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'home#top'
  get 'home/about'
  get '/search' => 'search#search'
  post 'follow/:id' => 'relationships#follow', as: 'follow' # フォローする
  post 'unfollow/:id' => 'relationships#unfollow', as: 'unfollow' # フォロー外す
  resources :users, only: [:show ,:edit ,:update ,:index, :destroy ] do
    resource :relationships, only: [:create, :destroy]
  get 'followings' => 'relationships#followings', as: 'followings'
  get 'followers' => 'relationships#followers', as: 'followers'
  end
  resources :books, only: [:new, :create,:index, :show, :destroy ,:edit ,:update] do
   resources :book_comments, only: [:create, :destroy]
   resource :favorites, only: [:create, :destroy]
 end
 end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
   belongs_to :user
   #attachment :image
   has_many :favorites, dependent: :destroy
   has_many :book_comments, dependent: :destroy
  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end
   validates :title, presence: true
   validates :body, presence: true ,length:{maximum:200}
end

app/models/book_comment.rb
class BookComment < ApplicationRecord
  belongs_to :user
  belongs_to :book
  validates :comment, presence: true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :book
end

app/models/relationship.rb
class Relationship < ApplicationRecord
    belongs_to :follower, class_name: "User"
    belongs_to :followed, class_name: "User"
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy
  has_many :follower, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :followed, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  has_many :following_user, through: :follower, source: :followed
  has_many :follower_user, through: :followed, source: :follower
  attachment :profile_image

# ユーザーをフォローする
def follow(user_id)
  follower.create(followed_id: user_id)
end

# ユーザーのフォローを外す
def unfollow(user_id)
  follower.find_by(followed_id: user_id).destroy
end

# フォローしていればtrueを返す
def following?(user)
  following_user.include?(user)
end

  validates :name, presence: true,length:{minimum:2,maximum:20},uniqueness: true
  validates :introduction,length:{maximum:50}
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :authenticate_user!

  def new
   @book = Book.new
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
     if  @book.save
        flash[:notice] = "Book was successfully created."
        redirect_to book_path(@book)
     else
      @books = Book.all
      @user = current_user
      render "books/index"
     end
  end

  def index
     @books = Book.all
     @user = current_user
     @book = Book.new
  end

  def show
     @book = Book.find(params[:id])
     @user = @book.user
     @book_new = Book.new
     @book_comment = BookComment.new
     @book_comments = @book.book_comments.order(created_at: :desc)
  end

  def edit
      @book = Book.find(params[:id])
      if @book.user == current_user
          render "edit"
      else
          redirect_to books_path
      end
  end

  def destroy
    book = Book.find(params[:id])
    book.destroy
    redirect_to books_path
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
    flash[:notice] = "Book was successfully updated."
    redirect_to book_path(@book)
    else
    flash[:notice] = "Book was errored."
    render :edit
    end
  end

  private

  def book_params
    params.require(:book).permit(:title, :body)
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
      before_action :authenticate_user!
    def create
    @book = Book.find(params[:book_id])
    favorite = current_user.favorites.new(book_id: @book.id)
    favorite.save
    end

    def destroy
    @book = Book.find(params[:book_id])
    favorite = current_user.favorites.find_by(book_id: @book.id)
    favorite.destroy
    end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def top
  end

  def about
  end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  def search
    @model = params["search"]["model"]#選択したmodelを@modelに代入
    @value = params["search"]["value"]#検索にかけた文字列(ここではvalue)を@valueに代入
    @how = params["search"]["how"]#選択した検索方法howを@howに代入
    @datas = search_for(@how, @model, @value)      #search_forの引数にインスタンス変数を定義
  end

  private

  def match(model, value)                     #def search_forでhowがmatchだった場合の処理
    if model == 'user'                        #modelがuserの場合の処理
      User.where(name: value)                 #whereでvalueと完全一致するnameを探します
      elsif model == 'book'
      Book.where(title: value)
    end
  end

  def forward(model, value)
    if model == 'user'
      User.where("name LIKE ?", "#{value}%")
    elsif model == 'book'
      Book.where("title LIKE ?", "#{value}%")
    end
  end

  def backward(model, value)
    if model == 'user'
      User.where("name LIKE ?", "%#{value}")
    elsif model == 'book'
      Book.where("title LIKE ?", "%#{value}")
    end
  end

  def partical(model, value)
    if model == 'user'
      User.where("name LIKE ?", "%#{value}%")
    elsif model == 'book'
      Book.where("title LIKE ?", "%#{value}%")
    end
  end

  def search_for(how, model, value)#searchアクションで定義した情報が引数に入っている
    case how                      #検索方法のhowの中身がどれなのかwhenの条件分岐の中から探す処理
    when 'match'
      match(model, value)          #検索方法の引数に(model, value)を定義している
    when 'forward'                        #例えばhowがmatchの場合は def match の処理に進みます
      forward(model, value)
    when 'backward'
      backward(model, value)
    when 'partical'
      partical(model, value)
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!



  def new
  end

  def create
  end

  def index
    @users = User.all
    @user = current_user
    @book = Book.new
  end

  def show
    @user = User.find(params[:id])
    @books = @user.books
    @book = Book.new
    @users = User.all
  end

  def edit
    @user = User.find(params[:id])
    if @user == current_user
    render "edit"
    else
    redirect_to user_path(current_user)
    end
  end

  def update
    @user = User.find(params[:id])
    if  @user.update(user_params)
    flash[:notice] = "User was successfully updated."
    redirect_to user_path(@user)
    else
      flash[:notice] = "User was errored."
      render "users/edit"
    end
  end

  def destroy
  end

  def followings
    @followings = @user.following_users
  end

  def followers
    @followers = @user.follower_users
  end

private

  def user_params
    params.require(:user).permit(:name,:introduction, :profile_image)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

app/helpers/book_commentｓ_helper.rb
module BookCommentｓHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
　　　<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

   <body>
  <% flash.each do |key, value| %>
  <%= content_tag(:div, value, class: "#{key}") %>
  <% end %>

    <header class="p-3 mb-2 bg-dark text-white">
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">


           <%= link_to "Bookers", root_path , class: 'navbar-brand'%>


          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
    <ul class="navbar-nav ml-auto">

     <% if user_signed_in? %>
      <li class="nav-item">
        <%= link_to "Home", user_path(current_user.id) , class: 'fas fa-home nav-link text-light ' %>
      </li>
      <li class="nav-item">
        <%= link_to "Users", users_path , class: 'fas fa-users nav-link text-light'%>
      </li>
      <li class="nav-item">
        <%= link_to "Books", books_path , class: 'fas fa-book-open nav-link text-light' %>
      </li>
      <li class="nav-item">
       <%= link_to "logout", destroy_user_session_path, method: :delete, class: 'fas fa-sign-out-alt nav-link text-light' %>
      </li>




    <% else %>
      <li class="nav-item">
      <%= link_to "Home", root_path , class: 'fas fa-home nav-link text-light '%>
      </li>
    　<li class="nav-item">
       <%= link_to "About", home_about_path , class: 'fas fa-link nav-link text-light' %>
      </li>
      <li class="nav-item">
       <%= link_to "sign up", new_user_registration_path , class:'fas fa-user-plus nav-link text-light'%>
      </li>
      <li class="nav-item">
        <%= link_to "login", new_user_session_path , class:'fas fa-sign-in-alt nav-link text-light'%>
      </li>
    <% end %>

   </ul>
          </div>
        </div>
      </nav>
    </header>

   <main class="mb-auto">
    <%= yield %>
  </main>

    <footer>
      <div class="container　mt-5">
        <div class="row">
          <div class="mx-auto">
            <p>CopyRight Infratop.inc</p>
          </div>
        </div>
      </div>
    </footer>

  </body>
</html>